### PR TITLE
Hollow Singleton

### PR DESCRIPTION
**Pull request by astralien3000**
@Elioty you should watch this repos.
I made a new type of Singleton that will really not use any memory.
Wooo ! Evil singletons that does not contain data will not use the 1 byte dedicated to them by C++ standard.

Of course, there is a lot of limitations for HollowSingletons (no non-static attributes, and no virtual methods), but it can be a good pattern for classes that handle mcu's register without more data.

Here is an example code that illustrates the difference : 
```c++
#include <iostream>
using namespace std;

#include <base/singleton.hpp>
#include <base/hollow_singleton.hpp>

class A : public SINGLETON <A> {
  friend SINGLETON <A>;
  A() {} // Singleton needs a defined constructor, but HollowSingleton don't need it => delete
  A(const A&) = delete;
public:
  void test(void) const {
    cout << "lool" << endl;
  }
};

int main(int, char**) {
  A& a = A::instance();
  a.test();
  return 0;
}
```

To compile this, you just need this kind of line : 
```bash
g++ -I/path/to/aversive++/include/dir -std=c++11 main.cpp -Os -DSINGLETON=HollowSingleton -o hs.elf && size hs.elf
g++ -I/path/to/aversive++/include/dir -std=c++11 main.cpp -Os -DSINGLETON=Singleton -o s.elf && size s.elf
```

The compiler also seems to be able to do more optimisation with HollowSingletons than with Singletons.

Any comment ?

### CODE REVIEW

**Comment by Elioty** [comment]
I made a minimal code on some online C++ compiler/shell to test it out:
```C++
#include <iostream>

using namespace std;

template<typename _BASE>
class HollowSingleton {
private:
    struct Checker : public _BASE {
        char check;
    };
    
protected:
    inline HollowSingleton(void) {
    }
    
    inline HollowSingleton(const HollowSingleton&) {
    }
    
public:
    static inline _BASE& instance(void) {
        static_assert(sizeof(Checker) == sizeof(char), "Error, HollowSingleton objects must be empty");
        return *((_BASE*)0);
    }
};

template<typename _BASE>
class Singleton {
protected:
    inline Singleton(void) {
    }
    
    inline Singleton(const Singleton&) {
    }

public:
    static inline _BASE& instance(void) {
        static _BASE inst;
        return inst;
    }
};

class A : public SINGLETON <A> {
    friend SINGLETON <A>;
    A() {} // Singleton needs a defined constructor, but HollowSingleton don't need it => delete
    A(const A&) = delete;
public:
    void test(void) const {
        cout << "lool" << endl;
    }
};

int main(int, char**) {
    A& a = A::instance();
    a.test();
    return 0;
}
```

And the results are:
```
sh-4.3$ g++ -std=c++11 -Os main.cpp -DSINGLETON=Singleton && size a.out && ./a.out
   text    data     bss     dec     hex filename
   2264     652     288    3204     c84 a.out
lool
sh-4.3$ g++ -std=c++11 -Os main.cpp -DSINGLETON=HollowSingleton && size a.out && ./a.out
   text    data     bss     dec     hex filename
   2033     636     280    2949     b85 a.out
lool
```

BEAST!!

However, what improvements for the code readability does it actually bring? I mean, can't you do just the same with a simple typename template argument with a class full of static constexpr attributes and static methods? You still need a typename template argument if you want to give your "instance" as parameter to a function. However, nice finding again ;) 

On another topic since we are on the singletons, you should tag the copy constructor in Singleton `= delete` and likewise for the `operator=` to make sure it's never used/automatically generated by the compiler. In HollowSingleton, you can actually tag all three (the default and copy constructor and the assignment operator) with `= delete`.

And one last note which is more general, it's about `static_assert`s, I think we should write them directly in the private section of the class (and not in some (static) method), the most at the top as possible. So when someone read the code, it's clearer that it applies to the actual class and not to a function/method call. And the most at the top so possible so you can see sooner what are the constraints on the template parameters when you read the code again. Should probably make an issue to discuss that matter though, don't you think?

**Comment by astralien3000** [comment]
I agree with you about static_assert in the private sections of classes, I tried, but in this case, it throws an error of "incomplete class" or something like that (you can try). It is quite normal in this particular case since the "Checker" class inherits from _BASE, which inherits from HollowSingleton. It makes a loop dependency.

**Comment by astralien3000** [comment]
About code readability, it may be usefull for devices that are on top of HAL. Instead of instanciating the object, you can get the singleton. And continue to use static polymorphism with it. I'm saying that, but the HollowSingleton don't call the constructor... So no init in this way. I have read about a way to call constructor, but I seemed quite dirty.

So yeah, I'm not sure it has great advantages against static methods.

And about the ` = delete` statement, good point, I will add it where it is useful.

**Comment by Elioty** [comment]
> I agree with you about static_assert in the private sections of classes, I tried, but in this case, it throws an error of "incomplete class" or something like that (you can try). It is quite normal in this particular case since the "Checker" class inherits from _BASE, which inherits from HollowSingleton. It makes a loop dependency.

Oh I see what you mean for this. But in the general case, we agree so, so far so good :)

> About code readability, it may be usefull for devices that are on top of HAL. Instead of instanciating the object, you can get the singleton. And continue to use static polymorphism with it. I'm saying that, but the HollowSingleton don't call the constructor... So no init in this way. I have read about a way to call constructor, but I seemed quite dirty.

> So yeah, I'm not sure it has great advantages against static methods.

Well, passing a class with only static constexpr attributes and static methods is pretty much the same on the "static polymorphism" standpoint. However, you don't need a function parameter so in the case the function is not inlined (or inlined but not optimised for some reasons), you are sure your parameter doesn't take a pointer space to store a reference (which would points to 0 with your HollowSingleton for instance) cause it's only a template arg and not a couple (template arg + function arg). But it's just getting back to the old C programmers vs modern C++ programmers clash/discussion.

And for the way to call the constructor, I guess you mean placement new, don't you?
Sould be something like that in your case: (CODE NOT TESTED)
```C++
template<typename _BASE>
class HollowSingleton {
private:
    struct Checker : public _BASE {
        char check;
    };

protected:
    inline HollowSingleton(void) {
    } // Do not =delete it this time

    HollowSingleton(const HollowSingleton&) = delete;
    HollowSingleton& operator=(const HollowSingleton&) = delete;

public:
    static inline _BASE& instance(void) {
        static_assert(sizeof(Checker) == sizeof(char), "Error, HollowSingleton objects must be empty");
        static _BASE* _this = new((_BASE*) 0) _BASE; // The cast is to prevent any warning, just in case
        return *((_BASE*) 0);
    }
};
```

> And about the `= delete` statement, good point, I will add it where it is useful.

Ok, great :)

**Comment by astralien3000** [comment]
> Well, passing a class with only static constexpr attributes and static methods is pretty much the same on the "static polymorphism" standpoint. However, you don't need a function parameter so in the case the function is not inlined (or inlined but not optimised for some reasons), you are sure your parameter doesn't take a pointer space to store a reference (which would points to 0 with your HollowSingleton for instance) cause it's only a template arg and not a couple (template arg + function arg). But it's just getting back to the old C programmers vs modern C++ programmers clash/discussion.

Maybe it is not more about optimisation than about global interface structure. Indeed, if several classes need to share the same interface, and some of the classes need to be instanciated (like the case of some Devices, or Streams), and others can be singletons as well as use static methods, it may be better to make them singleton, since you need to pass an object reference in the case of "compulsory instanciation".

I know static methods can be called like a normal methods : 
```c++
#include <iostream>
using namespace std;

class A {
public:
    static void test(void) {
        cout << "test" << endl;
    }
};

int main(int, char **)
{
    A::test();
    A a;
    a.test();
    return 0;
}
```

But it may appear weird to the user ? And I just noticed it is not incompatible with the use of HollowSingleton (to avoid several instanciation).

> And for the way to call the constructor, I guess you mean placement new, don't you?
Sould be something like that in your case: (CODE NOT TESTED)

Ok thanks, it was the kind of stuff I read. But there is an other problem : In your code, the constructor will be called every time the `instance` method will be called. I came up with the solution of using gcc attributes `constructor` and `destructor` (in other static methods), but I fear that it will do some weird stuff at some point. The first one is that the use of `std::cout` in constructor function causes a segfault. I suppose it is because the "GCC attibute - C style" constructors functions are called before any C++ class constructors. So... some care should be taken.

**Pull request closed without merging**
